PythonVersion="3.9.7"
pythonBuildCommandsFile="/tmp/zipdeploy/extracted/oryx-build-commands.txt"
packagedir=".python_packages/lib/site-packages"
OperationId="|zqCVa+9f7AQ=.56ab58d7_"
SourceDirectoryInBuildContainer="/tmp/8dac70add9c7f0e"
PlatformName="python"
CompressDestinationDir="false"
