from numpy import dtype

column_data_types = {
                     "SerialNumber": dtype("O"),
                     "ContractStartDate": dtype("O"),
                     "ContractEndDate": dtype("O"),
                     "PredictPulseContractType": dtype("O"),
                     "BatteryJarsPerTray": dtype("O"),
                     "BatteryTraysPerString": dtype("O"),
                     "BatteryMonitoring": dtype("O"),
                     "NumberOfCabinets": dtype("O"),
                     "ElecRooClean": dtype("O"),
                     "Upm2FanServDate": dtype("O"),
                     "Upm3FanServDate": dtype("O"),
                     "Upm4FanServDate": dtype("O"),
                     "LastServiceDate": dtype("O"),
                     "BattStrings": dtype("O"),
                     "BatteryCabinetType": dtype("O"),
                     "ElecAirFilter": dtype("O"),
                     "BattLastExchgDate": dtype("O"),
                     "BatteryDateCode": dtype("O"),
                     "BatteryInstallDate": dtype("O"),
                     "BattMfdDate": dtype("O"),
                     "FanServDate": dtype("O"),
                     "FanServDateElec": dtype("O"),
                     "Upm1FanServDate": dtype("O"),
                     "AcCapServDate": dtype("O"),
                     "DcCapServDate": dtype("O"),
                     "Model": dtype("O"),
                     "CtoNumber": dtype("O"),
                     "BatteryModel": dtype("O"),
                     "BatteryMfr": dtype("O"),
                     "BatteryType": dtype("O"),
                     "BatteryQuantity": dtype("O"),
                     "SiteName": dtype("O"),
                     "AddressLine1": dtype("O"),
                     "City": dtype("O"),
                     "State": dtype("O"),
                     "Country": dtype("O"),
                     "Zip": dtype("O"),
                     "InstalledDate": dtype("O"),
                     "WarrantyEndDate": dtype("O")
                     }
